services:
    php:
        build:
            context: ./docker/php/
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/app/
        depends_on:
            - mariadb
    node:
        image: node:18
        ports:
            - 5173:5173
        volumes:
            - ./:/app/
        working_dir: /app/
        command: "npm run dev"
    mariadb:
        image: mariadb:10.11
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MARIADB_DATABASE: "${DB_DATABASE}"
            MARIADB_USER: "${DB_USERNAME}"
            MARIADB_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./docker/mariadb/datas:/var/lib/mysql
            - ./docker/mariadb:/docker-entrypoint-initdb.d
    adminer:
        image: adminer
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
            ADMINER_DEFAULT_TYPE: mysql
    mailpit:
        image: axllent/mailpit:latest
        ports:
            - 1025:1025
            - 8025:8025
